### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by eoncins** [w3c/wai-presentations2all#23]
@slhenry It might be good to extend the terminology section, currently only 4 terms. It might be good also to include terminology from different regions such as captions (US) and Subtitles for the Deaf and Hard of Hearing (SDH). 

I would avoid to use the term "interpreters" to include all professionals 
**interpreters**
This includes sign language interpreters, cued speech transliterators, and others. Note that sign languages are different from spoken languages and there is not a one-to-one translation.

Some terms that could be added and/or defined:

- Alternative formats
- Alternative text
- Audio description
- Braille 
- Captions 
- Cued speech transliterators
- Easy to read information
- Large print
- Sign language
- Sign language interpreters
- Subtitles for the Deaf and Hard of Hearing (SDH)
- Transcriptions

Some terms could be extracted from:
http://www.edf-feph.org/sites/default/files/edf_guide_for_accessible_meetings_0.pdf
https://www.efhoh.org/wp-content/uploads/2019/06/EFHOH-Guidelines-for-Accessibility.pdf

**Comment by slhenry** [comment]
Thanks for the input, Estella. I'm going to address the terminology point here, and make separate GitHub issues for the others.

This terminology section was not intended to be comprehensive. It is intended to only include terms that are:
* needed for understanding the content on this page
* not otherwise explained when used in the page
* used without reference to more information

I've quoted the text from the resource for each term you listed:

* Alternative formats
> Participants might need material in alternative formats such as large print or braille.
...
> Sometimes you might use the Internet for providing alternative formats of materials during the presentation. For example, allowing people using screen readers or other assistive technologies to follow along with an online version of your displayed material.

_(examples of alternative formats given in the text)_

* Alternative text
> For example, provide alternative text for images and mark up headings.

_(not otherwise explained in this resource)_

* Audio description
> For example, provide captions and/or transcripts for audio, and provide audio description of visual information in videos. For guidance on creating accessible media, see [Making Audio and Video Media Accessible](https://www.w3.org/WAI/media/av/).

_(terminology explained in linked to resource)_

* Braille
> Participants might need material in alternative formats such as large print or braille.

_(I think almost all of our target audience knows what braille is?)_

* Captions
> For example, provide captions and/or transcripts for audio, and provide audio description of visual information in videos. For guidance on creating accessible media, see Making Audio and Video Media Accessible.

_(terminology explained in linked to resource)_

* Cued speech transliterators
> Terminology<br>interpreters - This includes sign language interpreters, cued speech transliterators, and others.

_(used only in a definition)_

* Easy to read information
> [not in resource]

* Large print
> Participants might need material in alternative formats such as large print or braille.

_(the concept of "large print" is self explanatory, and the specifics is beyond the scope of this resource)_

* Sign language
> Speak clearly - And avoid speaking too fast, so participants and sign language interpreters can better understand you and keep up.
> Terminology<br> interpreters - This includes sign language interpreters, cued speech transliterators, and others. Note that sign languages are different from spoken languages and there is not a one-to-one translation.

_(I think almost all of our target audience knows what sign language is?)_

* Sign language interpreters
> Terminology<br> interpreters - This includes sign language interpreters, cued speech transliterators, and others.

_(this is in the terminology section)_

* Subtitles for the Deaf and Hard of Hearing (SDH)
> [not in resource]

_(see related GitHub issue)_

* Transcriptions
> [not in resource]

Transcripts:
> For example, provide captions and/or transcripts for audio, and provide audio description of visual information in videos. For guidance on creating accessible media, see Making Audio and Video Media Accessible.
> … CART output can also be used to develop a transcript.
> Transcripts online can increase search engine optimization (SEO) for audio and video. Transcripts also have many other benefits.

_(I think almost all of our target audience knows what transcripts are?)_

**Comment by bakkenb** [comment]
Agree with all comments that Shawn has indicated here. Possible suggestion for the very last one on "Transcripts". Don't we have that defined in another resource as well. I think it is in the Making Video accessible resource where we define what a quality transcript should include. Could we add a link to the location where that is defined in the other resource?

Otherwise, I agree, the other terminology is not needed based on explanations in this thread.

**Comment by eoncins** [comment]
Thanks Shawn. Understanding that terminology is not intended to be included in the resource, then I agree with your proposal. Maybe I would add subtitles next to captions, see below: 

"Make media fully accessible — including audio and video used in sessions, and recordings of sessions provided afterwards
For example, provide captions/**subtitles** and/or transcripts for audio, and provide audio description of visual information in videos."

I would not avoid to use CART as this is a term broadly used in the US, but would include one of the following terms for the EU audiences:
"live subtitlers"
"speech-to-text interpreters"
"real-time intralingual subtitlers"

**Comment by slhenry** [comment]
Good. Thanks.

I edited the phrase to:

For example, provide [captions](#captions) _(called “intralingual subtitles” in some areas)_ and/or transcripts for audio, and provide audio description of visual information in videos. 


And edited the definition to:

:  _Captions (called “intralingual subtitles” in some areas)_ are a text version of speech and important non-speech audio. Live captioning in different areas is called different things, such as CART (Computer Aided Real–Time Captioning or Communication Access Realtime Translation), or real-time intralingual subtitling.<br>A _captioner_ (or “live subtitler”) is a professional who provides what is being said verbatim so that people can read the text output.<br>More information is in [Captions/Subtitles, in Making Audio and Video Media Accessible](/media/av/captions/).

Feel free to re-open this issue if you have additional input.
