### ISSUE TITLE
css to make dt bold

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-presentations2all#3]
I'm inclined to think we want this as the default for the site -- but happy for @yatil to decide.

**Comment by yatil** [comment]
I have seen some deliberate bolding inside of `<dt>`s. I think in general `<ul>` or `<ol>` have less overhead for screen reader users and can be used when deliberate bolding is needed.

I made a note in w3c/wai-website-design#124 and the new style will trickle down via the theme once it’s done. (Closing the issue here for simplicity 😀)
